<template>
  <Menu :active-name="thisMenu.key" width="auto" :open-names="['index','platformSetting','brandManage','financialManage','userManage']"  @on-select="createTab" style="height: 100%">
    <Submenu name="index" v-for="item in mainMenu[thisModel]">
      <template slot="title">
        <Icon type="ios-navigate"></Icon>
        {{item.title}}
      </template>
      <Menu-item :name="item2.key" v-for="item2 in item.childmenu">{{item2.title}}</Menu-item>
    </Submenu>
  </Menu>
</template>
<style>

</style>
<script>
    import mainMenuConfig from '../../config/main_menu.js'
    export default {
      data () {
            return {
                theme2: 'light',
                thisMenu:this.$store.state.tab.openComponentsList[this.$store.state.tab.thisPage.id],
                thisModel:this.$route.matched[0].path.substr(1),
                mainMenu:{
                  mm:{
                    mmIndex:{
                      key:"mmIndex",
                      title:"主页",
                      childmenu:{
                        mmDashboard:mainMenuConfig['mmDashboard'],
                        mmBigScreen:mainMenuConfig['mmBigScreen']
                      }
                    },
                    materialManager:{
                      key:"materialManager",
                      title:"物料管理",
                      childmenu:{
                        createMaterial:mainMenuConfig['createMaterial'],
                        materialList:mainMenuConfig['materialList'],
                        batchManagement:{
                          key:"",
                          title:"批次管理",
                        }
                      }
                    },
                    supplier:{
                      key:"supplier",
                      title:"供应商",
                      childmenu:{
                        createSupplier:{
                          key:"createSupplier",
                          title:"创建供应商",
                        },
                        supplierList:{
                          key:"",
                          title:"供应商列表",
                        }
                      }
                    },
                    purchaselManager:{
                      key:"purchaselManager",
                      title:"采购管理",
                      childmenu:{
                        createMaterial:{
                          key:"",
                          title:"采购申请",
                        },
                        materialList:{
                          key:"",
                          title:"采购订单创建",
                        },
                        batchManagement:{
                          key:"",
                          title:"采购记录",
                        },
                        batchManagement:{
                          key:"",
                          title:"询价报价",
                        }
                      }
                    },
                    inventoryManager:{
                      key:"inventoryManager",
                      title:"库存管理",
                      childmenu:{
                        createMaterial:{
                          key:"",
                          title:"入库",
                        },
                        materialList:{
                          key:"",
                          title:"出库",
                        },
                        batchManagement:{
                          key:"",
                          title:"转储",
                        },
                        batchManagement:{
                          key:"",
                          title:"盘点",
                        },
                        batchManagement:{
                          key:"",
                          title:"转储",
                        }
                      }
                    },
                    warehouselManager:{
                      key:"warehouselManager",
                      title:"仓库管理",
                      childmenu:{
                        createMaterial:{
                          key:"",
                          title:"创建物料",
                        },
                        materialList:{
                          key:"",
                          title:"物料列表",
                        },
                        batchManagement:{
                          key:"",
                          title:"批次管理",
                        }
                      }
                    }
                  },
                  ma:{
                    maIndex:{
                      key:"maIndex",
                      title:"主页",
                      childmenu:{
                        maDashboard:mainMenuConfig['maDashboard'],
                        maBigScreen:mainMenuConfig['maBigScreen']
                      }
                    },
                    maVoucher:{
                      key:"maVoucher",
                      title:"卡券",
                      childmenu:{
                        maCreateVoucher:mainMenuConfig['maCreateVoucher'],
                        maVoucherList:mainMenuConfig['maVoucherList'],
                        maHuiChangeCodeList:mainMenuConfig['maHuiChangeCodeList'],
                        maVoucherValidate:mainMenuConfig['maVoucherValidate'],
                        maVoucherAdvertising:mainMenuConfig['maVoucherAdvertising'],
                        maVoucherReport:mainMenuConfig['maVoucherReport']
                      }
                    },
                  }
                }
            }
      },
      methods:{
        getMenu(){

        },
        createTab(item){
          const _self = this;
          _self.openPage(mainMenuConfig[item].title,mainMenuConfig[item].key,mainMenuConfig[item].path);
          //console.log(_self.$store.state.model.menu[name].path);
          //this.router.push({ path: _self.$store.state.model.menu[name].path })
          console.log(item);
          
        },
        setThisMenu(){
          this.thisMenu = this.$store.state.tab.openComponentsList[this.$store.state.tab.thisPage.id];
        }
      },
      watch:{
        "$route":"setThisMenu"
      }
    }
</script>
