<template>
  <Menu theme="dark" :active-name="thisMenu.key" width="auto" :open-names="['index','platformSetting','brandManage','financialManage','userManage']"  @on-select="createTab" style="height: 100%">
    <Submenu name="index" v-for="item in mainMenu[thisModel]">
      <template slot="title">
        <Icon type="ios-navigate"></Icon>
        {{item.title}}
      </template>
      <Menu-item :name="item2.key" v-for="item2 in item.childmenu">{{item2.title}}</Menu-item>
    </Submenu>
  </Menu>
</template>
<style>

</style>
<script>
    import mainMenuConfig from '../../config/main_menu.js'
    export default {
      data () {
            return {
                theme2: 'light',
                thisMenu:this.$store.state.tab.openComponentsList[this.$store.state.tab.thisPage.id],
                thisModel:this.$route.matched[0].path.substr(1),
                mainMenu:{
                  mm:{
                    mmIndex:{
                      key:"mmIndex",
                      title:"主页",
                      childmenu:{
                        mmDashboard:mainMenuConfig['mmDashboard'],
                        mmBigScreen:mainMenuConfig['mmBigScreen']
                      }
                    },
                    materialManager:{
                      key:"materialManager",
                      title:"物料管理",
                      childmenu:{
                        createMaterial:mainMenuConfig['mmcreateMaterial'],
                        materialList:mainMenuConfig['mmmaterialList'],
                        batchManagement:{
                          key:"",
                          title:"批次管理",
                        }
                      }
                    },
                    supplier:{
                      key:"supplier",
                      title:"供应商",
                      childmenu:{
                        createSupplier:mainMenuConfig['mmcreateSupplier'],
                        supplierList:mainMenuConfig['mmsupplierList']
                      }
                    },
                    purchaselManager:{
                      key:"purchaselManager",
                      title:"采购管理",
                      childmenu:{
                        createMaterial:{
                          key:"",
                          title:"采购申请",
                        },
                        materialList:{
                          key:"",
                          title:"采购订单创建",
                        },
                        batchManagement:{
                          key:"",
                          title:"采购记录",
                        },
                        batchManagement:{
                          key:"",
                          title:"询价报价",
                        }
                      }
                    },
                    inventoryManager:{
                      key:"inventoryManager",
                      title:"库存管理",
                      childmenu:{
                        createMaterial:{
                          key:"",
                          title:"入库",
                        },
                        materialList:{
                          key:"",
                          title:"出库",
                        },
                        batchManagement:{
                          key:"",
                          title:"转储",
                        },
                        batchManagement:{
                          key:"",
                          title:"盘点",
                        },
                        batchManagement:{
                          key:"",
                          title:"转储",
                        }
                      }
                    },
                    warehouselManager:{
                      key:"warehouselManager",
                      title:"仓库管理",
                      childmenu:{
                        createMaterial:{
                          key:"",
                          title:"创建物料",
                        },
                        materialList:{
                          key:"",
                          title:"物料列表",
                        },
                        batchManagement:{
                          key:"",
                          title:"批次管理",
                        }
                      }
                    }
                  },
                  ma:{
                    maIndex:{
                      key:"maIndex",
                      title:"主页",
                      childmenu:{
                        maDashboard:mainMenuConfig['maDashboard'],
                        maBigScreen:mainMenuConfig['maBigScreen']
                      }
                    },
                    maVip:{
                      key:"maVip",
                      title:"会员",
                      childmenu:{
                        maVipData:mainMenuConfig['maVipData'],
                        maVipList:mainMenuConfig['maVipList'],
                        maVipSetting:mainMenuConfig['maVipSetting'],
                        maVipWechat:mainMenuConfig['maVipWechat'],
                        maVipAlipay:mainMenuConfig['maVipAlipay']
                      }
                    },
                    maVoucher:{
                      key:"maVoucher",
                      title:"卡券",
                      childmenu:{
                        maVoucherList:mainMenuConfig['maVoucherList'],
                        maHuiChangeCodeList:mainMenuConfig['maHuiChangeCodeList'],
                        maVoucherUseList:mainMenuConfig['maVoucherUseList'],
                        maVoucherAdvertising:mainMenuConfig['maVoucherAdvertising'],
                        maVoucherReport:mainMenuConfig['maVoucherReport']
                      }
                    },
                  },
                  wms:{
                    wmsIndex:{
                      key:"wmsIndex",
                      title:"主页",
                      childmenu:{
                        wmsDashboard:mainMenuConfig['maDashboard'],
                        wmsBigScreen:mainMenuConfig['maBigScreen']
                      }
                    },
                    wmsSet:{
                      key:"wmsSet",
                      title:"仓库配置",
                      childmenu:{
                        wmsSetList:mainMenuConfig['wmsSetList'],
                        wmsSetArea:mainMenuConfig['wmsSetArea'],
                        wmsSetLocation:mainMenuConfig['wmsSetLocation'],
                        wmsSetLocationType:mainMenuConfig['wmsSetLocationType']
                      }
                    },
                    wmsManage:{
                      key:"wmsManage",
                      title:"库内作业",
                      childmenu:{
                        wmsManageInventory:mainMenuConfig['wmsManageInventory'],
                        wmsManageRepair:mainMenuConfig['wmsManageRepair'],
                        wmsManageAllot:mainMenuConfig['wmsManageAllot'],
                        wmsManageMove:mainMenuConfig['wmsManageMove']
                      }
                    },
                    wmsInput:{
                      key:"wmsInput",
                      title:"验货入库",
                      childmenu:{
                        wmsInputPurchase:mainMenuConfig['wmsInputPurchase'],
                        wmsInputReturn:mainMenuConfig['wmsInputReturn'],
                        wmsInputAllot:mainMenuConfig['wmsInputAllot'],
                        wmsInputMove:mainMenuConfig['wmsInputMove'],
                        wmsInputOther:mainMenuConfig['wmsInputOther']
                      }
                    },
                    wmsOutput:{
                      key:"wmsInput",
                      title:"销货出库",
                      childmenu:{
                        wmsOutputPickList:mainMenuConfig['wmsOutputPickList'],
                        wmsOutputPick:mainMenuConfig['wmsOutputPick'],
                        //wmsOutputPack:mainMenuConfig['wmsOutputPack'],
                        wmsOutputDo:mainMenuConfig['wmsOutputDo'],
                        //wmsOutputList:mainMenuConfig['wmsOutputList'],
                        //wmsOutputWaitPick:mainMenuConfig['wmsOutputWaitPick'],
                        //wmsOutputWave:mainMenuConfig['wmsOutputWave'],
                      }
                    },
                    wmsStrategy:{
                      key:"wmsInput",
                      title:"仓内策略",
                      childmenu:{
                        wmsStrategyWave:mainMenuConfig['wmsStrategyWave'],
                        wmsStrategyWork:mainMenuConfig['wmsStrategyWork'],
                        wmsStrategyInventory:mainMenuConfig['wmsStrategyInventory'],
                        wmsStrategyBatch:mainMenuConfig['wmsStrategyBatch'],
                        wmsStrategyArea:mainMenuConfig['wmsStrategyArea']
                      }
                    }
                  },
                  tms:{
                    tmsFile:{
                      key:"tmsFile",
                      title:"基础档案",
                      childmenu:{
                        tmsFileCarrier:mainMenuConfig['tmsFileCarrier'],
                        // tmsFileDriver:mainMenuConfig['tmsFileDriver']
                      }
                    },
                    tmsOrder:{
                      key:"tmsOrder",
                      title:"订单中心",
                      childmenu:{
                        tmsOrderWait:mainMenuConfig['tmsOrderWait'],
                        tmsDelivery:mainMenuConfig['tmsDelivery'],
                        tmsAreaList:mainMenuConfig['tmsAreaList']
                      }
                    },
                    tmsData:{
                      key:"tmsData",
                      title:"数据中心",
                      childmenu:{
                        tmsDataHot:mainMenuConfig['tmsDataHot']
                      }
                    },
                    tmsTraffic:{
                      key:"tmsTraffic",
                      title:"运输设置",
                      childmenu:{
                        tmsTradingArea:mainMenuConfig['tmsTradingArea']
                      }
                    }
                  }
                }
            }
      },
      methods:{
        getMenu(){

        },
        createTab(item){
          const _self = this;
          _self.openPage(mainMenuConfig[item].title,mainMenuConfig[item].key,mainMenuConfig[item].path);
          //console.log(_self.$store.state.model.menu[name].path);
          //this.router.push({ path: _self.$store.state.model.menu[name].path })
          console.log(item);
          
        },
        setThisMenu(){
          this.thisMenu = this.$store.state.tab.openComponentsList[this.$store.state.tab.thisPage.id];
        }
      },
      watch:{
        "$route":"setThisMenu"
      }
    }
</script>
